base_url = "https://cufezhusy.github.io/szhu.github.io/"

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/issue-2/", name = "About"},
]
