base_url = "https://cufezhusy.github.io/"
theme = "even"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]
[extra]
generate_feeds = true
feed_filenames = "$BASE_URL/rss.xml"
even_title = "Cufezhusy's Blog"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags/my-life/", name = "My Life"},
    {url = "$BASE_URL/issue-2/", name = "About"},
]
