base_url = "https://cufezhusy.github.io/"
theme = "even"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[extra]
even_title = "且将新火试新茶，诗酒趁年华。| Brew new tea with fresh fire, savoring poetry and wine while time still favors us."
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags/my-life/", name = "My Life"},
    {url = "$BASE_URL/issue-2/", name = "About"},
]
